version: '3.5'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${myip:-127.0.0.1}:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_CREATE_TOPICS: "stock-on-hand:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  atmoz-sftp:
      image: atmoz/sftp
      volumes:
          - ${mydir:-/tmp/upload/}:/home/toothless/upload
      ports:
          - "2222:22"
      command: toothless:hiccup:1001
