server.port: 0

spring.application.name: vinsleo-spring-cloud-soh

spring.cloud.stream:
    bindings:
        output:
            destination: "stock-on-hand"
            contentType: "application/text"
    kafka.binder:
        brokers: "localhost"
        defaultBrokerPort: 9092
        zkNodes: "localhost"
        defaultZkPort: 2181
        configuration:
            security.protocol: PLAINTEXT
            commit.interval.ms: 1000
            default:
                key.serde: "org.apache.kafka.common.serialization.Serdes$StringSerde"
                value.serde: "org.apache.kafka.common.serialization.Serdes$StringSerde"

# Ensure the details here match the docker-compose.yml
sftp:
    factory:
        host: 127.0.0.1
        port: 2222
        username: toothless
        password: hiccup
        allow-unknown-keys: true
    remoteDir: "/upload/"
    localDir: "./data"
    filename-pattern: "*.csv"

file:
    consumer.mode: "lines"

trigger:
    fixed-delay: 3
    initial-delay: 10

logging:
    level:
        root: "warn"
        org.springframework: "info"
        uk.co.argos: "debug"
