#FIXME: SET Sensible defaults
server.port: 0

spring.application.name: ipt-service-soh-source


spring.cloud.stream:
    bindings:
        stock-on-hand:
            destination: "Argos-dev-IPT-SOH"
            contentType: "application/json"
        stock-on-hand-filtered:
            destination: "Argos-dev-IPT-Filtered-SOH"
            contentType: "application/json"
    kafka.binder:
        brokers: "localhost"
        defaultBrokerPort: 9092
        zkNodes: "localhost"
        defaultZkPort: 2181
        configuration:
            security.protocol: PLAINTEXT
            commit.interval.ms: 1000
            default:
                key.serde: "org.apache.kafka.common.serialization.Serdes$StringSerde"
                value.serde: "org.apache.kafka.common.serialization.Serdes$StringSerde"

spring.datasource:
    url: "jdbc:postgresql://localhost:5432/intake_planning"
    #FIXME: Use Embedded Vault to fetch the credentials
    username: owner-intake-planning
    password: P@ssw0rd

spring.flyway:
    schemas: "ipt_soh"

file:
    consumer.mode: "lines"

sftp:
    factory:
        host: 127.0.0.1
        port: 2222
        #FIXME: Use Embedded Vault to fetch the credentials
        username: toothless
        password: hiccup
        allow-unknown-keys: true
    remoteDir: "/upload/stock-on-hand/"
    localDir: "./data"
    filename-pattern: "*.csv"

trigger:
    fixed-delay: 3
    initial-delay: 10

logging:
    level:
        root: "warn"
        org.springframework: "info"
        uk.co.argos: "debug"
